USERNAME_LOCATOR: 'username'
PASSWORD_LOCATOR: 'password'
LOGIN_BUTTON_LOCATOR: '//*[@id="popContainer"]/div/div[1]/div/div[2]/form/div[5]/div/div/span/button'
SEARCH_KEY_LOCATOR: 'name'

BASE_URL: 'http://bed.test.cnzxa.cn'